### ISSUE TITLE
[BUG] Can't download more than one subtitle

### ISSUE THREAD

**Issue by 3boodr** [anidl/funimation-downloader-nx#10]
i can't download more than a one subtitle pls help 
btw i download subtitles only and it only downloads the first subtitle so i have to download them one by one

![sc](https://user-images.githubusercontent.com/64892095/81162170-6a078c00-8f95-11ea-8b30-71e3fd0f312f.PNG)

**Comment by darkhelmet2016** [comment]
Not sure if this is really a bug, shows only usually have one set of subtitles on funi just different formats for different platforms. Closed captions for English dubs when provided and subtitles for Japanese audio.

**Comment by shinji257** [comment]
According to the website the above episode only has English subs.  I have yet to see a video on Funimation have anything more.  If you see an episode with more than just English subs then post a link or show a screencap on the website that shows it had more than that.

![image](https://user-images.githubusercontent.com/261005/91303095-81050080-e775-11ea-8a11-ec4c86414493.png)
