### ISSUE TITLE
which features do you want?

### ISSUE THREAD

**Issue by izu-co** [anidl/funimation-downloader-nx#100]
Let's get straight to the point: `are there any features you want the cli to have?`

**Comment by OryWareKyrie** [comment]
not a suggestion for CLI but wouldn't a channel on Discord be good? I read that you're not a big fan of the telegram. it is better for discussing new ideas and solutions.

:smiley_cat: I think someone has already proposed this. well I don't know 100%

**Comment by DragonVsKira** [comment]
Put anime in folder of the anime name
So something like this “video/Fairytale/season 1”
Or just 
“video/Fairytale”
If u can’t it all good just my Me
If it Just  me wanting this future you can skip it no point in adding it if it’s just me lol :(

**Comment by OryWareKyrie** [comment]
> Put anime in folder of the anime name
> So something like this “video/Fairytale/season 1”
> Or just
> “video/Fairytale”
> If u can’t it all good just my Me
> If it Just me wanting this future you can skip it no point in adding it if it’s just me lol :(

Whats? kkkkkk

**Comment by DragonVsKira** [comment]
@OryWareKyrie do u not get what im saying ?

**Comment by OryWareKyrie** [comment]
> @OryWareKyrie do u not get what im saying ?

not at the beginning but now yes rsrsrsrs

**Comment by OryWareKyrie** [comment]
> Put anime in folder of the anime name
> So something like this “video/Fairytale/season 1”
> Or just
> “video/Fairytale”
> If u can’t it all good
> If it Just me wanting this future you can skip it no point in adding it if it’s just me lol :(

by the way great idea. izu-co can add this function?

**Comment by izu-co** [comment]
@DragonVsKira @OryWareKyrie 

With the new release, you can use the command (the `--fileName` option is important) to use relative paths.
`node .\funi.js -s 124389 -e 1,14 -q 1 --fileName '${showTitle}\\${season}\\[Funimation] ${episode} [${height}p]'`
**Make sure to use your OS path separator!**
Result:
![Result](https://user-images.githubusercontent.com/57068530/132108412-5dced1b9-a9cc-45ca-8101-6cda0484b603.png)

**Comment by izu-co** [comment]
By the way, I closed the issue, if you want anything just message me over at github@izuco.dev

**Comment by izu-co** [comment]
> not a suggestion for CLI but wouldn't a channel on Discord be good? I read that you're not a big fan of the telegram. it is better for discussing new ideas and solutions.
Here ya go!
https://discord.gg/qEpbWen5vq
