### ISSUE TITLE
HTTPError 403 Unable to download videos

### ISSUE THREAD

**Issue by zCrispy** [anidl/funimation-downloader-nx#103]

**Comment by zCrispy** [comment]
Accidently pressed enter when making this post, but I have had this problem where im unable to download episodes 75-291 of DBZ and im dont know how to fix this. sorry

**Comment by izu-co** [comment]
Please run the program again and use `--debug`. Also, please provide the default information.

**Comment by zCrispy** [comment]
I typed and entered --debug and its has brought up a list of options. Also what is the default information. Sorry and thank you.

**Comment by bgette** [comment]
tape your command -s xxxxx -e x **--debug**

**Comment by zCrispy** [comment]
Hi, it finished the debug. What should I be looking for? Thank you

**Comment by OryWareKyrie** [comment]
> Hi, it finished the debug. What should I be looking for? Thank you

must have a .txt file in the folder add it here

**Comment by zCrispy** [comment]
Hi, sorry where do I find the text file. (I tried it again and i dont think it has made one for both) Thank you

**Comment by OryWareKyrie** [comment]
> Hi, sorry where do I find the text file. (I tried it again and i dont think it has made one for both) Thank you

is inside the folder. send the command here please I'll test it

**Comment by zCrispy** [comment]
Sorry I dont have a text file. The command I used was "node funi -s 24278 -e 75-291 --debug" (If this is what you meant)

**Comment by OryWareKyrie** [comment]
> Sorry I dont have a text file. The command I used was "node funi -s 24278 -e 75-291 --debug" (If this is what you meant)

Manin now I realized that is not saving the .txt debug. about your problem I can't help since I don't have a VPN. here in BR there is no dragon ball in the funimation

**Comment by zCrispy** [comment]
Thats ok and thanks. Ill just try a couple of things.

**Comment by zCrispy** [comment]
Is there a chance that i have to buy premium plus? Because I cant view the video and I cant watch up to episode 74 which is where its cuts off.

**Comment by izu-co** [comment]
You can download all the videos with this tool, you can watch with your account on Funimation.

So if you have a free account, you can't download premium content.

**Comment by zCrispy** [comment]
Got it. So i just have to buy premium and reauthenticate?

**Comment by izu-co** [comment]
I don't think that reauthenticating is necessary, but you can try if it doesn't work.

**Comment by zCrispy** [comment]
ok thank you very much

**Comment by izu-co** [comment]
No problem!
