### ISSUE TITLE
[BUG] Debian 11 - Errors when starting post-processing

### ISSUE THREAD

**Issue by N3EOP** [anidl/funimation-downloader-nx#104]
** Main info: **

Script version: Funimation Downloader NX 4.10.0
Show ID: 594522
Episode ID: 1
Command used: node funi --trace-warnings -s 594522 -q 0 --allSubs --allDubs -e 1

** Additional Info: **

System is up-to-date Debian 11.

Dependencies:

Node.js v12.22.5.

$ npm version
{
  'funimation-downloader-nx': '4.10.0',
  npm: '7.5.2',
  node: '12.22.5',
  v8: '7.8.279.23-node.56',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.3',
  http_parser: '2.9.4',
  openssl: '1.1.1k',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}

ffmpeg version 4.3.2-0+deb11u2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)

$ mkvmerge -V
mkvmerge v52.0.0 ('Secret For The Mad') 64-bit

Clip from output:

[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!
(node:18023) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at downloadStreams (/home/jamie/funimation-downloader-nx/funi.js:747:116)
    at async getEpisode (/home/jamie/funimation-downloader-nx/funi.js:435:13)
    at async getShow (/home/jamie/funimation-downloader-nx/funi.js:291:13)
(node:18023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
#

**Comment by N3EOP** [comment]
Closed without comment?

**Comment by izu-co** [comment]
It does that automatically when I referee to it in a commit. That means that I believe it should be fixed within the commit. If not, feel free to reopen with new information.

**Comment by N3EOP** [comment]
OK; thanks.  I hadn't noticed an update.  I'll check it out.

**Comment by N3EOP** [comment]
That fixed it!  Thanks for the prompt update.
