### ISSUE TITLE
MP4 Muxing Incorrect Language [BUG] 

### ISSUE THREAD

**Issue by JudgeUAu** [anidl/funimation-downloader-nx#105]
** Main info: **

Script version: 4.9.5
Show ID:  847520
Episode ID: all
Command used: node funi.js -s 847520 -q 0 --subLang enUS --dub jaJP enUS --mp4 --all

** Additional Info: **
Labels Japanese Audio as English

**Comment by izu-co** [comment]
Is this an issue with the subtitles or the dub language?

**Comment by izu-co** [comment]
My energy to work on this project is currently quite low, so I only work on program breaking bugs. 

But rest assured, I will come back to this sooner or later. Or is it `really` important to you?

**Comment by JudgeUAu** [comment]
hey mate...honestly take your time with it its not really an issue...the problem is with the DUB. also i have noticed its only on some content but not all. but when ever you get around to it no need to rush it.
