### ISSUE TITLE
[ERROR] RequestError 301: Moved Permanently [BUG] 

### ISSUE THREAD

**Issue by levaculik2** [anidl/funimation-downloader-nx#111]
** Main info: **

Script version: funimation-downloader-nx-4.10.2-linux64
Show ID: 371172
Episode ID: 0001
Command used: ./funi --s 371172 -e 0001 -q 10 --dub "jaJP" --allSubs --mp4

** Additional Info: **

I went to download it today because I hadn't downloaded anything from the funimation site for a while. When I came across this error "[ERROR] RequestError 301: Moved Permanently" I thought it was because I was using an outdated version. was giving the same error. I authenticated to see if it resolved and even then nothing.

**Comment by izu-co** [comment]
Can you check that you got the ID right?

**Comment by levaculik2** [comment]
true I put one more number and had not noticed instead of putting the ID 37172 and put ID 371172.nor had realized.I apologize for the error.
