### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by ItsRainingHP** [anidl/funimation-downloader-nx#116]
** Main info: **

Script version: 4.12.3
Show ID: Any, 1036022, 594522
Episode ID: All of them
Command used: node funi.js -s ######## --nosubs -q 0 -e # --mp4

** Additional Info: **
I continue to get this error no matter which video I use. At first I thought it was because I was using an older version but since redownloading everything and setting up I continue to get this thrown error on every video. 
![image](https://user-images.githubusercontent.com/79205731/134201747-0aa9a1eb-5400-4fc1-b0b9-b7a1d7a4b147.png)

**Comment by izu-co** [comment]
Is some other process using the file by any chance? Do you use extra Drive or a NAS?

**Comment by izu-co** [comment]
And I would need the command (-s and -e)

**Comment by ItsRainingHP** [comment]
![image](https://user-images.githubusercontent.com/79205731/134203893-165cdebd-117b-45d1-b5b4-e7fe9297f6c9.png)

I wasn't trying to hide it. I was just trying to point out I have tried commands for multiple episodes and shows and still get the error.

**Comment by izu-co** [comment]
I think this is an you issue. Are you sure that no process is accessing it (like Anti-Virus etc)?

**Comment by ItsRainingHP** [comment]
I will try closing out to the barebones on my PC and run it from different drives to see if the issue persists and follow up.

**Comment by ItsRainingHP** [comment]
Update for all: Definitely a virus scan error. Adding a folder exception to Avast fixed the issue.

**Comment by ItsRainingHP** [comment]
Update for all: Definitely a virus scan error. Adding a folder exception to Avast fixed the issue.
