### ISSUE TITLE
Readme.md is incorrect

### ISSUE THREAD

**Issue by ItsRainingHP** [anidl/funimation-downloader-nx#117]
** Main info: **

Paths Configuration
By default this application uses the following paths to programs (main executables):

./bin/ffmpeg.exe
./bin/mkvmerge.exe
To change these paths you need to edit bin-path.yml in ./config/ directory.

** Additional Info: **

bin-path.yml
ffmpeg: "./bin/ffmpeg/ffmpeg.exe"
mkvmerge: "./bin/mkvtoolnix/mkvmerge.exe"

**Comment by izu-co** [comment]
Will do later
