### ISSUE TITLE
mkvmerge and ffmpeg not found?

### ISSUE THREAD

**Issue by Anit0** [anidl/funimation-downloader-nx#118]
All though it's there but it's skiping?

[INFO] Downloading subtitles...
[INFO] Subtitles downloaded!
[WARN] MKVMerge not found, skip using this...
[WARN] FFmpeg not found, skip using this...

**Comment by bgette** [comment]
config/bin-path.yml

```
ffmpeg: "./bin/ffmpeg.exe"
mkvmerge: "./bin/mkvmerge.exe"
```

**Comment by OryWareKyrie** [comment]
@Anit0 you are not running on windows 11 are you? the same happened to me on win 11

**Comment by Anit0** [comment]
@bgette Thanks bro the config had issue.. now it's fixed

**Comment by izu-co** [comment]
> @Anit0 you are not running on windows 11 are you? the same happened to me on win 11

About that: I got no way to test it lol

**Comment by TheBlackJ3sus** [comment]
> @Anit0 you are not running on windows 11 are you? the same happened to me on win 11

Adding ffmpeg & mkvmerge to path in Environment Variables solved this for me on win 11.

**Comment by BaseCrunch** [comment]
I can confirm that adding ffmpeg to Environment Variables fixes the problem for windows 11


1. search up "Environment Variables"

2. a new window will appear then at the bottom click on "Environment Variables"

3.  Find "Path" variable click on "Edit" while "Path" variable is selected

4. Click on "New" now paste in the location path where ffmpeg is for mine is "C:\Users\bweak\Downloads\multi-downloader-nx-2.0.0-win64\multi-downloader-nx-2.0.0-win64\bin\ffmpeg" 

5.  Repeat steps 3-4 on "System variables" then click on "Ok" then "Ok" again to exit it out now you have to restart your pc
