### ISSUE TITLE
[BUG] Can't download japanese dub: ERROR: Timeout awaiting 'request' for 60000ms

### ISSUE THREAD

**Issue by Atemu** [anidl/funimation-downloader-nx#119]
** Main info: **

Script version: 7e35bdbe5afc15ec7aa6b60d61f02b410b1a9f5b
Show ID: 1319611
Episode ID: 1
Command used: `node funi.js -s 1319611 --skipmux --allSubs --dub jaJP --all -q 10`

** Additional Info: **

```
[WARN] Part 1: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
```

is printed for all parts of the current queue, over and over again.

When using --novids, it tries to download a huge amount of data. I stopped it at 14% where it already downloaded 2.2GiB which is insane and definitely not an audio stream. Perhaps that's why.

Only happens with jaJP, en dub works just fine.

**Comment by izu-co** [comment]
Can't confirm. The command is working fine for me!
