### ISSUE TITLE
Can't download zhMN shows

### ISSUE THREAD

**Issue by STRATOS99K** [anidl/funimation-downloader-nx#123]
** Main info: **

Script version:  4.12.4
Show ID:  2773547
Episode ID: 
Command used: funi -s 2773547 -e 1 -q 0 --allSubs --dub zhMN

While trying to download Chinese shows I get this message "Episodes not selected!", it also happens with the defective 1715847

**Comment by STRATOS99K** [comment]
> Please, can you give me the console output?

> node funi -s 2773547 -e 1 -q 0 --allSubs --dub zhMN

=== Funimation Downloader NX 4.12.4 ===

[#2773547] Ancient Girls Frame (2021)
[INFO] Episodes not selected!

I did download the source code again, I have no problems with this version 4.8.1
Is there a command to give you a better output?

**Comment by izu-co** [comment]
Can you give me the output of both version with the ˋ—debugˋ flag. 
Make sure do delete your keys or to revoke them afterwards.

**Comment by STRATOS99K** [comment]
> Can you give me the output of both version with the `—debug` flag. Make sure do delete your keys or to revoke them afterwards.
[4.8.1.txt](https://github.com/anidl/funimation-downloader-nx/files/7325225/4.8.1.txt)
[4.12.4.txt](https://github.com/anidl/funimation-downloader-nx/files/7325226/4.12.4.txt)

Both without login, tried with the defective since I need no account for ep 1
Command for both
node funi -s 1715847 -e 1 -q 0 --dub zhMN --debug

**Comment by izu-co** [comment]
Strange. I don't see any changes to the way the data is requested between the two version.
Can you give me the exact commit that you are using, please? (Since there is no official 4.8.1 release)
