### ISSUE TITLE
--fileName not working in linux

### ISSUE THREAD

**Issue by Anit0** [anidl/funimation-downloader-nx#128]
i am trying to auto rename the file with given command. but it's not working on linux. But it's working on windows version Ripper. But not working in linux one.

Command: **_./funi -s 2794128 -q 7 -e 3 --mks --allSubs --allDubs --fileName "[Anime] ${showTitle} - ${episode} [${height}p][Multiple Subtitle]"_**

this issue showing...

[INFO] Selected layer: 7 (1280x720) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2605271/a1ebfce3-2f7d-4058-9501-85229df38a88strnv-hl152_streaming_video_1280_720_4500000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjYwNTI3MS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM1MDkxOTkwfX19XX0_&Signature=jqw~X8rCFAQy3Y5BQ7kps7-JIt3LUHOnEjhwLqLyMZKrQGyYjBJ79uTkohPjsONu1w5g3m1Xn5IlRq0hsX~DyV5fsQOacbf2BxC~YUXm~13dShQQSgqfXkyC2H4nWY2Bo~lX0AIBoiLQVIut9wnLFcOUoo9Fed4hSIsLZpVIzz1RZkCa-sxU2i5Cqs57aHQqqbKf0ed~AM9McAfeLAirJW8tM7uGKzthn6FBFySlyH8XrcXb4ThHH0to~0m~g3pKA6oa2IGKffbXfdB4ee8hF3lAiGxdRFqxKgl4AFv7hr-UvTdySTcsNPYMhyJYWBBbg3Jc~hOAqKxpW94aarqPjw__&rt=1425007
(node:54562) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at parseFileName (/snapshot/funimation-downloader-nx/funi.js)
    at downloadStreams (/snapshot/funimation-downloader-nx/funi.js)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getEpisode (/snapshot/funimation-downloader-nx/funi.js)
    at async getShow (/snapshot/funimation-downloader-nx/funi.js)
(Use `funi --trace-warnings ...` to show where the warning was created)
(node:54562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54562) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by izu-co** [comment]
Closed due to inactivity.

**Comment by sl1pkn07** [comment]
@izu-co same issue here, but in my case not chow the variable in the filename

~~~
└───╼  for i in $(seq 01 12); do node index.js --service crunchy -s GR79JZ046 -e $i -q 0 --subLang es --fileName "[sL1] ${title} - ${episode}"; done

=== Multi Downloader NX 2.0.9 ===

[INFO] USER: Anonymous
[INFO] Your Country: ES

  [S:GR79JZ046] Hitoribocchi no Marumaruseikatsu (Season: 1) [SUB]
 ✓[01|E:GR9VKZ7W6] 1 - My First Confession [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [02|E:GR5P4103R] 2 - Actually, Thank You [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [03|E:GRME5NKWY] 3 - Getting It Across by Spinning Your Wheels [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [04|E:G6ME5NVVR] 4 - I'll Be Your Apprentice [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [05|E:GRQWEEV4R] 5 - Happens All the Time [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [06|E:GY4PX5W06] 6 - Summer Comes in 5-7-5 [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [07|E:GYKE7EDGY] 7 - Gentle Tears [23m57s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [08|E:GRNVDJ3W6] 8 - Welcome Back from Elsewhere [23m42s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [09|E:GY8D01Z0Y] 9 - Perfect Curry Pancakes [23m42s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [10|E:GYP5JV3WY] 10 - No One Said That Before [23m42s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [11|E:GYP5J3XDY] 11 - From Tap-Tap to Print-Print [23m42s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en
  [12|E:GYJ0E8G26] 12 - Maybe I Just Might [23m42s, SUB, STREAM]
    - Subtitles: es-419, es, pt-BR, fr, de, ar, it, ru, en

[INFO] Requesting: [GR9VKZ7W6] Hitoribocchi no Marumaruseikatsu - 1 - My First Confession
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/jpn/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.com/evs1/43636ac86495bc76ee35a59999444d33/assets/5cfba6b26fcd91b30bb5821186789536_,3649131.mp4,3649132.mp4,3649130.mp4,3649128.mp4,3649129.mp4,3649127.mp4,.urlset/master.m3u8?Expires=1640029974&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS80MzYzNmFjODY0OTViYzc2ZWUzNWE1OTk5OTQ0NGQzMy9hc3NldHMvNWNmYmE2YjI2ZmNkOTFiMzBiYjU4MjExODY3ODk1MzZfLDM2NDkxMzEubXA0LDM2NDkxMzIubXA0LDM2NDkxMzAubXA0LDM2NDkxMjgubXA0LDM2NDkxMjkubXA0LDM2NDkxMjcubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAwMjk5NzR9fX1dfQ__&Signature=MYNblVv9ZmW1oVJxvhLOVZNn2DafkBS-J4Y7It~zkRx0xElKMayc-LH4tw4wX6lia~PMIjDIhwEm7H4cVSrlU~U6L~G4hOdbwOCeqTl7tTci~pbOgEeI~KTgEdKzYCa~CLeFd95T-g0fKmI8zGsnjswdHzxxy8Ke~cq8G68W8IGOMQ6Sl48vh8mif7X5pwrHmUpydtJ7cvOKP4iMejZWjLkbaN94arm~zXdnzmDIfO9Igh4bh79ZViVCnjAtzAIpYZjFZNwzwWcob95FDXAprwLaRUx1Y-bKh4qrJDVwiwKcuRge5urzs~55jCzN32wgnPf-SamFESO7ZaT3iovXOQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/jpn/-)
[INFO] Servers available:
        pl.crunchyroll.com (ll-prod)
        pl.crunchyroll.com (fy-prod)
[INFO] Available qualities:
        [1] 144x80 (191KiB/s)
        [2] 428x240 (550KiB/s)
        [3] 640x360 (1068KiB/s)
        [4] 848x480 (2038KiB/s)
        [5] 1280x720 (4027KiB/s)
        [6] 1920x1080 (7919KiB/s)
[INFO] Selected quality: 1920x1080 @ pl.crunchyroll.com (ll-prod)
[INFO] Output filename: [sL1]  - .jpn
[INFO] Total parts in stream: 718 (72*10)
[INFO] Saving stream to «/media/COSAS/aplicaciones/multi-downloader-nx/lib/videos/[sL1]  - .jpn.ts»...
---cut---
~~~
