### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LuisLucas32** [anidl/funimation-downloader-nx#14]
** Main info: **
I am unable to find and download "The Ones Within"
Here is the link to the show: https://www.funimation.com/shows/the-ones-within/
![image](https://user-images.githubusercontent.com/66101521/84849719-c9cc6a80-b00a-11ea-851c-603b64e2ed2d.png)

Script version: 4.6.0
Show ID: N/A
Episode ID: N/A

**Comment by OgnistyPoland** [comment]
Here: https://i.imgur.com/Ox0X4ba.png
[#917765] The Ones Within (2019)

**Comment by LuisLucas32** [comment]
What a legend! Thanks a ton :P
