### ISSUE TITLE
[BUG] options.agent

### ISSUE THREAD

**Issue by mightymercado** [anidl/funimation-downloader-nx#15]
I encountered this error when running `node funi.js --auth --proxy-auth "user:pass" --proxy "https://x.x.x.x:4000"` after entering auth details.

```
[ERROR] TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `_events`
```

**Comment by LuisLucas32** [comment]
You are supposed to give it your own proxy. That is just an example of how to use it

**Comment by anidl** [comment]
proxy dont work right now
