### ISSUE TITLE
[BUG] Unable to find the ID of Gleipnir

### ISSUE THREAD

**Issue by LuisLucas32** [anidl/funimation-downloader-nx#16]
** Main info: **
I can't find the ID of the Gleipnir but I can find the IDs of other shows like My Hero Academia.
Link to the show: https://www.funimation.com/shows/gleipnir/
Script version: 4.6.0
Show ID: n/a
Episode ID: n/a
![image](https://user-images.githubusercontent.com/66101521/85831900-e6238200-b743-11ea-9fdf-f1fa8a1abd10.png)

** Additional Info: **

**Comment by XxUnkn0wnxX** [comment]
not really a bug if it works works for me, try doing a re-auth for the downloader 
![Screen Shot 2020-07-27 at 10 50 37 am](https://user-images.githubusercontent.com/2242880/88493952-1dad7480-cff7-11ea-9e49-8ce2153a605b.jpg)
but downloader is having issues atm seems it fails every 10 parts it downloads, issue here: #19
