### ISSUE TITLE
add support to animelab? (Funimation closings its doors in AU)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/funimation-downloader-nx#2]
Funimation & animelab are the same company & its easier to download from animelab as you can watch & download the anime even without subscription but you need to know the link EG:

Darwins Game https://dcgm6i50yfgtk.cloudfront.net/madABR_21089_e29eda147d8344d/dash/1080.mp4
& the audio is seperate:  https://dcgm6i50yfgtk.cloudfront.net/madABR_21089_e29eda147d8344d/dash/audio.mp4

for Jap release they hardcode the subtitles into the video.

![Screen Shot 2020-01-26 at 11 26 40 am](https://user-images.githubusercontent.com/2242880/73129043-c66e1d80-402e-11ea-8a13-142d681770f2.jpg)

@anidl maybe you could find a way to build this into this downloader or maybe make a seperate one that can fetch the streams for each episode & mux them? because downloading each episode is painstakingly slow, when trying to download the whole show & episode at a time.

i'm not sure how i can automate this... as i'm my coding skills are extremely low to none.

**Comment by OgnistyPoland** [comment]
You can use internet download manager

**Comment by XxUnkn0wnxX** [comment]
@OgnistyPoland 
i know that, but i would want something that can auto download whole seasons instead of going from page to page downloading each EP at a time. & something that auto muxes & labels each episode.

**Comment by anidl** [comment]
If I have time for this then probably why not
