### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Student2503** [anidl/funimation-downloader-nx#20]
[ERROR] HTTPError 403: Forbidden
root@4fb6653002dc:/content/funimation-downloader-nx/funimation-downloader-nx#

**Comment by xXOCsonicLeEpicMemeXx** [comment]
I have the same issue valveplsfix

**Comment by nijave** [comment]
Did you do `node funi.js --auth` and make sure that's saved inside the container?
https://github.com/anidl/funimation-downloader-nx#authentication

**Comment by anidl** [comment]
this app dont work outside funi regions
