### ISSUE TITLE
Only the first 2 episodes download properly

### ISSUE THREAD

**Issue by xXOCsonicLeEpicMemeXx** [anidl/funimation-downloader-nx#21]
Only the first 2 episodes download properly, The rest just give me an http 403 error. 
I tried changing the server, That didn't help any. Got any ideas? This is what I'm tryna download incase it helps any (Presuming it might be that the download servers lack the right files or they are formatted differently).
https://www.funimation.com/shows/danganronpa-3-the-end-of-hopes-peak-high-school/?qid=

**Comment by anidl** [comment]
should be fixed with latest version
