### ISSUE TITLE
Download Episode With Non-Integer ID

### ISSUE THREAD

**Issue by JakeGuy11** [anidl/funimation-downloader-nx#23]
When listing all the episodes in the selected series, it lists
`[001] Series - Title (Time) [Options]
[002] Series - Title (Time) [Options]
[003] Series - Title (Time) [Options]`

However, OVAs have
`[V001] Series - Title (Time) [Options]`

I've tried lots of different syntax options (V001, ova#01, etc.) but nothing seems to work. How do I download something like this?

**Comment by nijave** [comment]
I was about to grab something with M001 using `-e m001` successfully

**Comment by gudeat** [comment]
Have you tried -e v1 ? I succeed in downloading [V002] with  -e v2 as well as  [M001] with m1.

**Comment by Evoley** [comment]
I just encountered this with Hellsing Ultimate. I've tried the same as @JakeGuy11 but just says episodes not selected
