### ISSUE TITLE
Am I stupid or something?

### ISSUE THREAD

**Issue by renafromhigurashi** [anidl/funimation-downloader-nx#28]
I'm like 45% sure I did everything right and installed all the modules... why am I getting this issue?

PS, I have no idea what I'm doing and I don't understand any of this techno-jargon. I just want to download anime.
![help me why am i retarded](https://user-images.githubusercontent.com/72621383/95610047-515c4000-0a25-11eb-8fe2-e593f7a95dbc.PNG)

**Comment by Student2503** [comment]
same

**Comment by STRATOS99K** [comment]
If you are looking for my hero academia then, funi --search "My Hero Academia"
funi -s 124389 -e 1 -q 0 --sub   example to download ep 1
funi -s 124389 -e 1 -q 0 --simul for simulcast version, just a couple of examples

**Comment by anidl** [comment]
use `funi` for binary version and `node funi` for source version
