### ISSUE TITLE
ffmpeg \ mkvmerge error?

### ISSUE THREAD

**Issue by jnyfiveoh** [anidl/funimation-downloader-nx#3]
After episode download completion saw the following:

[WARN] MKVMerge not found, skip using this...
[WARN] FFmpeg not found, skip using this...

Confirmed both exe files are in appropriate folder path within bin.

Has anyone else encountered this issue?

**Comment by XxUnkn0wnxX** [comment]
what does it say in your `bin-path.yml`? might need to hard link the paths in there. be sure your using the latest stable build of ffmpeg & mkvmerge.
make sure it's the CLI binary version of ffpmeg & mkvmerge cannot be GUI

**Comment by jnyfiveoh** [comment]
ffmpeg: ./bin/ffmpeg
mkvmerge: ./bin/mkvmerge

in each folder is ffmpeg.exe and mkvmerge.exe for command line use and not the gui exe

I will try updating ffmpeg and see what happens

**Comment by Jougan** [comment]
Make sure both ffmpeg.exe and mkvmerge.exe are directly in the bin folder, and not in their own folders in bin folder

**Comment by jnyfiveoh** [comment]
> Make sure both ffmpeg.exe and mkvmerge.exe are directly in the bin folder, and not in their own folders in bin folder

Still encountering same issue.  Started happening when I updated NodeJS to most recent version
Confirmed exes are in the appropriate locations even created duplicate exe files.
One thing that I did notice is running 'npm i' again I got the following;
created a lockfile as package-lock.json. You should commit this file

**Comment by Jougan** [comment]
I did have it working, but decided to start fresh to see what's going on. Now i'm getting the same issue as you. Will keep looking into it.

**Comment by Atemu** [comment]
Make sure you adjust the paths inside the YAML file to have the .exe extension.

**Comment by jnyfiveoh** [comment]
> Make sure you adjust the paths inside the YAML file to have the .exe extension.

Changed the path inside bin-path.yml to:
ffmpeg: ./bin/ffmpeg.exe
mkvmerge: ./bin/mkvmerge.exe

No joy...

**Comment by Atemu** [comment]
But the paths exist if you try to `ls` them from the same working dir you run funi.js from?

**Comment by jnyfiveoh** [comment]
> But the paths exist if you try to `ls` them from the same working dir you run funi.js from?

Not following,

Please note I am using Windows 10

**Comment by jnyfiveoh** [comment]
Im not following,
Please note I am using Windows 10

Attached image of main folder and bin folder contents
![bin](https://user-images.githubusercontent.com/47425729/74591228-49054f80-4fd3-11ea-898b-4849deb4d7f3.PNG)

![Main](https://user-images.githubusercontent.com/47425729/74591222-2d9a4480-4fd3-11ea-9512-a45f4b071706.PNG)

**Comment by jnyfiveoh** [comment]
> Im not following,
> Please note I am using Windows 10
> 
> Attached image of main folder and bin folder contents and bin-path.yml file
> ![Main](https://user-images.githubusercontent.com/47425729/74591222-2d9a4480-4fd3-11ea-9512-a45f4b071706.PNG)
> 
> ![bin](https://user-images.githubusercontent.com/47425729/74591228-49054f80-4fd3-11ea-898b-4849deb4d7f3.PNG)
> 
> ![image](https://user-images.githubusercontent.com/47425729/74591248-84a01980-4fd3-11ea-982b-a5029e71b5ed.png)

**Comment by jnyfiveoh** [comment]
Even tried this configurations
![image](https://user-images.githubusercontent.com/47425729/74591433-30963480-4fd5-11ea-9fee-d6bf11dbfc1f.png)

**Comment by Atemu** [comment]
They need to either go into the `bin/` subdirectory or you edit the paths to be ./ffmpeg etc.

**Comment by jnyfiveoh** [comment]
> They need to either go into the `bin/` subdirectory or you edit the paths to be ./ffmpeg etc.

Yes I understand that.  I created duplicate .exe files and copied them in the root folder as well as the bin folder, etc.  
For some reason, it seems the *.js script is ignoring the bin-path.yml config file.

**Comment by Atemu** [comment]
And your working dir is the same as funi.js is in?

**Comment by Jougan** [comment]
Here is a fix, I replaced the config code in funi.js with the previous versions. This zip contains the now working funi.js, and config-main.yml. Put config-main.yml in the config folder 
[Funi-DL.zip](https://github.com/anidl/funimation-downloader-nx/files/4213694/Funi-DL.zip)

**Comment by jnyfiveoh** [comment]
> And your working dir is the same as funi.js is in?

If you are asking if I am using the node command from the same location as the funi.js file, then yes.

**Comment by jnyfiveoh** [comment]
> Here is a fix, I replaced the config code in funi.js with the previous versions. This zip contains the now working funi.js, and config-main.yml. Put config-main.yml in the config folder
> [Funi-DL.zip](https://github.com/anidl/funimation-downloader-nx/files/4213694/Funi-DL.zip)

That completely broke  me.
#!/usr/bin/env node
 ^

SyntaxError: Invalid or unexpected token
 [90m    at wrapSafe (internal/modules/cjs/loader.js:1067:16) [39m
 [90m    at Module._compile (internal/modules/cjs/loader.js:1115:27) [39m
 [90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10) [39m
 [90m    at Module.load (internal/modules/cjs/loader.js:1000:32) [39m
 [90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14) [39m
 [90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) [39m
 [90m    at internal/main/run_main_module.js:17:47 [39m

**Comment by Jougan** [comment]
Strange. I just downloaded a fresh copy of funimation-downloader-nx 4.5.0, ran npm i, and replaced funi.js with the one from my .zip. Put config-main.yml in config folder, and put ffmpeg and mkvmerge in bin folder, and it worked. Try starting from scratch and see if it works.

**Comment by Jougan** [comment]
> > Here is a fix, I replaced the config code in funi.js with the previous versions. This zip contains the now working funi.js, and config-main.yml. Put config-main.yml in the config folder
> > [Funi-DL.zip](https://github.com/anidl/funimation-downloader-nx/files/4213694/Funi-DL.zip)
> 
> That completely broke me.
> #!/usr/bin/env node
> ^
> 
> SyntaxError: Invalid or unexpected token
> [90m at wrapSafe (internal/modules/cjs/loader.js:1067:16) [39m
> [90m at Module._compile (internal/modules/cjs/loader.js:1115:27) [39m
> [90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10) [39m
> [90m at Module.load (internal/modules/cjs/loader.js:1000:32) [39m
> [90m at Function.Module._load (internal/modules/cjs/loader.js:899:14) [39m
> [90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) [39m
> [90m at internal/main/run_main_module.js:17:47 [39m

Do you have Discord? It'd be easier to assist you on there

**Comment by jnyfiveoh** [comment]
Discord, yes.

**Comment by Jougan** [comment]
> Discord, yes.

Add me when you can, Jougan#7001

**Comment by jnyfiveoh** [comment]
Sweet! Issue resolved.  Jougan's update \ patch resolved the issue.  One item of note.  Using most recent version of NodeJS and NPM will break it.

Per Jougan's suggestion of downgrading to node 12.4.0 and npm 6.9.0 made the script functional again.

-Thanks for the assist

**Comment by anidl** [comment]
https://github.com/anidl/funimation-downloader-nx/releases/tag/4.5.1
should be fixed with latest release
