### ISSUE TITLE
Req: Title naming with season/episode numbering

### ISSUE THREAD

**Issue by N3EOP** [anidl/funimation-downloader-nx#30]
I'm downloading SAO, and I can't get the naming the way I'd like it.

$ node funi -s 594522 -q 0 -e S002 --sub

gives output named
[Funimation] Sword Art Online - 18.5 [1080p].mkv

The season/episode info is available:
[INFO] Selected Episodes: S002

[INFO] Sword Art Online - S3E18.5 - Recollection

And this is exactly how I'd like my files to be named.  As it is, I can only download one season at a time, since it will try to create episode 1 again for the new season.

Any ideas?

**Comment by anidl** [comment]
use title command for title naming
episode naming supported using ep command
see help command

**Comment by Nicknakin** [comment]
> 
> 
> use title command for title naming
> episode naming supported using ep command
> see help command

Is there a chance you could give us an example? I've had this issue in the past.

**Comment by izu-co** [comment]
You mean an example on how to name files?
I think I‘ve made the system easier, so have you taken a look at the help?

**Comment by Nicknakin** [comment]
I actually haven't lately, I'll do that.

**Comment by izu-co** [comment]
Do you need a link?

**Comment by Nicknakin** [comment]
No, looks like in your fork it would be something to the effect of 
--fileName "title Sseasonxepisode"
?

**Comment by izu-co** [comment]
Yes that seams right

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
