### ISSUE TITLE
Can't download anymore

### ISSUE THREAD

**Issue by STRATOS99K** [anidl/funimation-downloader-nx#32]
(node:7748) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at downloadStreams (C:\Users\Admin\Downloads\funimation-downloader-nx-4.6.1-win64\funimation-downloader-nx-4.6.1-win64\funi.js:489:67)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async getEpisode (C:\Users\Admin\Downloads\funimation-downloader-nx-4.6.1-win64\funimation-downloader-nx-4.6.1-win64\funi.js:446:13)
    at async getShow (C:\Users\Admin\Downloads\funimation-downloader-nx-4.6.1-win64\funimation-downloader-nx-4.6.1-win64\funi.js:339:13)
(node:7748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I did download the zip again to check by the way, any show that I try would give this error

**Comment by cimmy01** [comment]
I'm having the same issue

**Comment by Golumpa** [comment]
So as i needed to get this working asap i just did a quick dirty bypass to get the bot working again, it seems funi has moved from cloudfront for its m3u8 playlist hosting to its own funimationsvc.com with session keys and shit.

NOTE: The below bypass is not a fix but will make it so you can download again...

Line 476: Add funisvc to the mainServersList, Not sure if this is actually needed but i did it anyway.
`let mainServersList = [
        'vmfst-api.prd.funimationsvc.com',
        'd132fumi6di1wa.cloudfront.net',
        'funiprod.akamaized.net'
    ];`

Line 489: Change the $ to a .
`let plLayerId = parseInt(s.uri.match(/_Layer(\d+)\.m3u8./)[1]);`

Line 500: Change the != condition to == so it doesn't fail. This just skips the check really.
`if(plStreams[plServer][plLayerId] && plStreams[plServer][plLayerId] == plUrlDl){`

**Comment by STRATOS99K** [comment]
> So as i needed to get this working asap i just did a quick dirty bypass to get the bot working again, it seems funi has moved from cloudfront for its m3u8 playlist hosting to its own funimationsvc.com with session keys and shit.
> 
> NOTE: The below bypass is not a fix but will make it so you can download again...

I just compiled and it works, thank you!

**Comment by cimmy01** [comment]
Awesome Thank You!

**Comment by XxUnkn0wnxX** [comment]
this change has made it harder, now I don't have a good backup...

as I used to use youtube-dl or ffmpeg in case this downloader gets issues..

![Screen Shot 2020-10-17 at 1 04 55 am](https://user-images.githubusercontent.com/2242880/96268705-19509080-1015-11eb-8e47-890563d4c75d.jpg)

![Screen Shot 2020-10-17 at 1 05 17 am](https://user-images.githubusercontent.com/2242880/96268710-1ce41780-1015-11eb-9abc-c4fc74a43050.jpg)

& I'm not sure how to get ffmpeg to read this 
as it says `Unable to open key file https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/2281735/Japanese/2281735_Japanese_3ba1e8d2-910a-eb11-82a8-dd291e252010_Layer10_0.key`

do I need to pass cookies to it now? even if I have the m3u8 playlist file locally?

**Comment by anidl** [comment]
https://github.com/anidl/funimation-downloader-nx/releases/tag/4.7.0-beta.1
