### ISSUE TITLE
[BUG] cli-defaults.yml, video layer not being phrased (config ignored)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/funimation-downloader-nx#36]
** Main info: **

Script version: 4.7.0-beta.2
Show ID: 592641
Episode ID: 24

I've noticed that the script fails to load the quality parameter found in `cli-defaults.yml`
I have it set to `videoLayer: 0` however when I run `node funi.js -s 592641 -e 24 --mks` it downloads at video layer 7 (720p)

**Comment by Golumpa** [comment]
There is no such layer as 0. It goes from 1 to 10.

**Comment by izu-co** [comment]
This has been resolved.
