### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Akropos** [anidl/funimation-downloader-nx#37]
Version: 4.6.2
No matter what show I tried to find, it would always return "[INFO] Total shows found: 0"
I did the --auth, installed everything that was needed, I ran the "npm i" command without any errors.
PS: I used the "funi --search "My Hero" command, I didn't include the node part, cause it would freak out and type out this mess: 
"Error: Cannot find module 'C:\Users\100da\Desktop\funimation-downloader-nx-4.6.1-win64\funimation-downloader-nx-4.6.1-win64\funi'

[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []"

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
