### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dragoon91786** [anidl/funimation-downloader-nx#38]
Script version: 4.7.0-beta.2
Show ID: #1173233
Episode ID: 0004-0006
![Bug Pic 1](https://user-images.githubusercontent.com/48355906/98986550-eac1ba80-24d9-11eb-8247-61eb7ca74f13.png)
![Bug Pic 2](https://user-images.githubusercontent.com/48355906/98986551-eb5a5100-24d9-11eb-8e8b-b2c63d4df195.png)

** Additional Info: **

Worked on Episodes 0001-0003, but stopped working on 0004-0006.

**Comment by Dragoon91786** [comment]
I attempted changing the server via -x 1 and -x 2, but the problem did not resolve.

**Comment by STRATOS99K** [comment]
It is working for me, I did a test try using this
funi -s 1173233 -e 5 -q 0 --sub if you are using --ep to change the name make sure that -e 5 -q 0 --sub go first, I had a similar problem while using the rename commands --ep, --suffix

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
