### ISSUE TITLE
Support for Funimation LATAM

### ISSUE THREAD

**Issue by arbarbosa1979** [anidl/funimation-downloader-nx#41]
I would like to ask you to include support for funimation LATAM -  Mexico/Brazil (Spanish and Portuguese)

**Comment by H3rdell** [comment]
Any news on this? I'm also interested in support for Funimation LATAM - Mexico/Brazil (Spanish and Portuguese).

Sample link:

https://www.funimation.com/pt-br/shows/death-note-2/?qid=None

**Comment by AnAppleforlife** [comment]
It should be possible with the current code base.

**Comment by Oujiii** [comment]
It doesn't work without a VPN or proxy, I think the server used is the one that is restricted to the US.
