### ISSUE TITLE
Can you please actually explain how to install and use this?

### ISSUE THREAD

**Issue by PinkRei** [anidl/funimation-downloader-nx#45]
I have installed all the prerequisites successfully. I went to node_modules/npm/, where the package.json file is, and ran "npm i". Now I have the "funimation-downloader-nx-4.6.1-win64" folder sitting in my downloads folder. What am I supposed to do with the contents of this folder? To I add the exe to my PATH? Do I put it somewhere in the nodejs directory? Do I run a certain command with node?
When I open the command prompt in the "funimation-downloader-nx-4.6.1-win64" folder and type "node funi" I get this: 
![image](https://user-images.githubusercontent.com/45299008/109240941-aced5700-7795-11eb-820c-b526d50ffaa2.png)
typing "funi" on its own appears to work, but when I try to actually download anything using the command you show in the readme, I get all this, which I can't even fit in one image:
![image](https://user-images.githubusercontent.com/45299008/109241217-3dc43280-7796-11eb-871a-9a94f2db812f.png)
![image](https://user-images.githubusercontent.com/45299008/109241268-53395c80-7796-11eb-8b17-b2156afd3c15.png)

If I'm supposed to open the command prompt in a directory other than where the "cmd-here.bat" is, then where? If I need to install this with node somehow, then how? Why is there no documentation anywhere in this project? In a nutshell, what am I supposed to do?

**Comment by LordEliteDragon** [comment]
go to Funimation Downloader NX b type: npm i

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
