### ISSUE TITLE
[Token Not Set]

### ISSUE THREAD

**Issue by xixhienxix** [anidl/funimation-downloader-nx#47]
doesnt matter the command i try to excecute i always get  a 
[Token Not Set]
[ERROR] HTTPError 403: forbidden

i have tryed to log using the funi -auth
but after my login and password set i still get the HTTPError 403: forbidden

**Comment by DragonVsKira** [comment]
re login will fix it

**Comment by xixhienxix** [comment]
running again the command, node funi.js --auth, gives me the same output, TOKEN NOT SET and after i write mi username and pasword it says Error Access Forbidden

**Comment by xixhienxix** [comment]
i got the 1 month suscription of premmiun acces

**Comment by DragonVsKira** [comment]
did u do is

Prerequisites
NodeJS >= 12.4.0 (https://nodejs.org/)
NPM >= 6.9.0 (https://www.npmjs.org/)
ffmpeg >= 4.0.0 (https://www.videohelp.com/software/ffmpeg)
MKVToolNix >= 20.0.0 (https://www.videohelp.com/software/MKVToolNix)

**Comment by xixhienxix** [comment]
yes

**Comment by DragonVsKira** [comment]
i do not no them because im use GUI that i made it look like this
[https://drive.google.com/file/d/1yKj_OWuwfae9o_csepGLJqekTaH1LBKN/view?usp=sharing](url)

**Comment by JakeGuy11** [comment]
This may sound like a fairly obvious thing, but you keep mentioning your *username*, when you should be entering your *email*, so that might be the problem.\
I'm not familiar with the GUI, so if it does prompt you for your username instead of your email, that's something that needs fixing.

**Comment by DragonVsKira** [comment]
> This may sound like a fairly obvious thing, but you keep mentioning your _username_, when you should be entering your _email_, so that might be the problem.
> I'm not familiar with the GUI, so if it does prompt you for your username instead of your email, that's something that needs fixing.

that because i made the GUI no one is familiar with it lol

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
