### ISSUE TITLE
Seasons

### ISSUE THREAD

**Issue by bobbime** [anidl/funimation-downloader-nx#49]
** Main info: **

Script version: 4.6.1
Show ID: The Promised Neverland (S2)
Episode ID: 

** Additional Info: **
I notice that some animes have seasons at which their episodes start from 1 again (the anime has same id, different seasons/eps though), meaning they aren't consistently numerical from season 1 to season 2. Issue is that if I wanted to get the 8th episode from season 2 of TPM, there would need to be an extra query: `season=<num>`. 
Example:
https://prod-api-funimationnow.dadcdigital.com/api/funimation/episodes/?limit=-1&sort=order&sort_direction=ASC&title_id=800858&season=2&language=English
However, this brings up a second issue. This api doesn't work for fetching the second season. (Please let me know which directories/queries could work though in the case I'm wrong)

This api, though, which is built into the default funimation domain, works, which made me think, is funimation.com/api more reliable to use than the prod-api one to use for episodes?
https://www.funimation.com/api/episodes/watchnext/?title_id=800858&season=2&sort=order&sort_direction=ASC

Thanks for reading lol

**Comment by AnAppleforlife** [comment]
I don't really know why they are using 2 APIs in the first place. Maybe one for retrieving files and one for everything else? But then again you kind of have to search through the files to display the videos...

I would appreciate if anyone has information about why they are using 2 and when they use which API.

**Comment by darkhelmet2016** [comment]
Unless you have redeemed any of the digital codes from any of their products you probably should not be concerned with the digital api. Yes they are separate as one directly tied to your own cloud content.

**Comment by AnAppleforlife** [comment]
First of all, thanks for the explanation.

I am currently in the process of figuring out what they changed and how it worked in the first place. If I did mange to see through it, I might start to work on a fix.

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
