### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DragonVsKira** [anidl/funimation-downloader-nx#5]
** Main info: **

Script version: funimation-downloader-nx-4.5.1
Show ID: 1019573  BOFURI: I Don’t Want to Get Hurt, so I’ll Max Out My Defense
Episode ID: 9

** Additional Info: **
![funi](https://user-images.githubusercontent.com/35433196/77033998-f5857900-6965-11ea-88fb-e6c9e903526e.PNG)

**Comment by storm134** [comment]
Not a bug episode 9 dubbed has not been release, you get this error when the video is either not there or there is a issue with. when i get it i always check funimation website to make sure the video is working.
