### ISSUE TITLE
unhandled exception on new episodes with a premium subscription [BUG] 

### ISSUE THREAD

**Issue by cimmy01** [anidl/funimation-downloader-nx#52]
!-- Please <fill in the placeholders.-->

** Main info: [INFO] Kuma Kuma Kuma Bear - S1E11 - Bear, Fights Squid (?)
[INFO] Available streams (Non-Encrypted):
[#1176451] Japanese [Simulcast]
[#1407326] English [Simulcast] (selected)
(node:7628) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at downloadStreams (U:\GitHub\funimation-downloader-nx-master\funi.js:413:66)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getEpisode (U:\GitHub\funimation-downloader-nx-master\funi.js:368:13)
    at async getShow (U:\GitHub\funimation-downloader-nx-master\funi.js:251:13)
(node:7628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Script version: 4.7.0 beta.2
Show ID: 1176414
Episode ID: 0011

** Additional Info: **

**Comment by Golumpa** [comment]
Seems as though funimation has done some changes recently. The video and audio streams are no longer in a single m3u8 file for one and the m3u8 files are now no longer in the /signed api endpoint.

**Comment by cimmy01** [comment]
It is annoying to say the least. Do you think a fix is possible?

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
