### ISSUE TITLE
[TS file not fully downloaded] 

### ISSUE THREAD

**Issue by heptahex** [anidl/funimation-downloader-nx#53]
** Main info: **

Script version: 4.7.0-beta.2
Show ID: 1321634 [Mushoku Tensei : Jobless Reincarnation]
Episode ID: 0001 [Episode 1, Jobless Reincarnation]

I'm having trouble with downloading. I can't download the complete video. I only got the incomplete m3u8 video file, [Funimation] Mushoku Tensei_ Jobless Reincarnation - 01 [1080p].ts.resume . But I could download completely when quality level is low( -q 1 ). I got these errors when I download the previous (-q 1) video with (-q 10). I also doubt that it is because of my slow internet speed. While I'm downloading, I also got warnings and errors. Please check the image below. Someone solve my issue, please.

![Error Message and Warning](https://user-images.githubusercontent.com/82636866/114989314-52cb6100-9ebd-11eb-9734-88950cd49986.png)

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
