### ISSUE TITLE
[Request] add support for tsparts in batch?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/funimation-downloader-nx#62]
i noticed the Crunchyroll downloader has this argument & in config, `--tsparts           Download ts parts in batch`
can this function be added for Funimation downloader? as downloading 10 parts a time is rather too slow for me & my connection speed can handle multithreaded connections.

I'd like to be able to download multiple parts simultaneously not just 10 at a time...

**Comment by AnAppleforlife** [comment]
Hey there. #60 introduces the new option '--partsize' which adds the requested functionality.

**Comment by XxUnkn0wnxX** [comment]
however, I don't think it reads it from the config though @AnAppleforlife AnAppleforlife setting `partsize: 30` in `cli-defaults.yml` doesn't seem to take effect...

**Comment by AnAppleforlife** [comment]
It does now accept partsize from cli-defaults.

**Comment by XxUnkn0wnxX** [comment]
![Screen Shot 2021-05-06 at 1 31 50 am](https://user-images.githubusercontent.com/2242880/117167937-0fed1100-ae0b-11eb-9cc2-47385d5a3221.jpg)

I think you set the wrong track.. the video file got set instead of audio...
no errors or warnings this time though...
