### ISSUE TITLE
[BUG] Token not set(compile problem)

### ISSUE THREAD

**Issue by STRATOS99K** [anidl/funimation-downloader-nx#65]
Getting this after compiling for windows

Node js 12.4.0

Getting this message after a successful authentication and getting the token but this message appears next, I can't download premium content since I keep getting token not set

** Main info: **
(node:6792) UnhandledPromiseRejectionWarning: Error: File or directory 'C:\**\funimation-downloader-nx-master\config\token.yml' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:446:17)
    at openFromSnapshot (pkg/prelude/bootstrap.js:487:29)
    at Object.openSync (pkg/prelude/bootstrap.js:511:12)
    at Object.writeFileSync (fs.js:1387:35)
    at auth (C:\snapshot\funimation-downloader-nx-master\funi.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `funi --trace-warnings ...` to show where the warning was created)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AnAppleforlife** [comment]
Did you use the javascript version or the build?

**Comment by STRATOS99K** [comment]
> Did you use the javascript version or the build?
> 
> If you use the build can you include a screenshot of the directory the funimation downloader is in?

Visual studio code, run build task -> npm: build-win64
I did download the code from this master branch for that after installing all dependencies
https://imgur.com/a/MG0b6Em

**Comment by AnAppleforlife** [comment]
I think there is a problem with the build. Can you try to use the normal version? (PS: there are some issues with the current code base. I tried to fix as much as possible in my pull request).

**Comment by STRATOS99K** [comment]
> I think there is a problem with the build. Can you try to use the normal version? (PS: there are some issues with the current code base. I tried to fix as much as possible in my pull request).

I did compile with 14.5.0 got the same error while trying to log in
and this while trying to download a free show otherside picnic E1

(node:6656) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:375:7)
    at downloadStreams (C:\snapshot\funimation-downloader-nx-master\funi.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getEpisode (C:\snapshot\funimation-downloader-nx-master\funi.js)
    at async getShow (C:\snapshot\funimation-downloader-nx-master\funi.js)
(Use `funi --trace-warnings ...` to show where the warning was created)
(node:6656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Press any key to continue . . .

**Comment by AnAppleforlife** [comment]
No I want you to not compile the code, but rather use the nodejs version.

**Comment by STRATOS99K** [comment]
> No I want you to not compile the code, but rather use the nodejs version.

js version for this master branch:
login and token works fine, old streams work fine, new streams I get a 6000ms timeout and never downloads.

js version for your fork:
everything is working like a charm! both new streams and old streams.
If you could add support for multisubs that would be awesome.

I see 3 subs with the new streams this season :
english_full.vtt
spanishlatinamerica_full.vtt
portuguesebrazil_full.vtt

**Comment by AnAppleforlife** [comment]
Sorry for the late replay. Try my [fork](https://github.com/AnAppleforlife/funimation-downloader-nx). It fixes a lot of issues about the new episodes.
