### ISSUE TITLE
funi.js windows script host error

### ISSUE THREAD

**Issue by thegreatuploader** [anidl/funimation-downloader-nx#66]
I'm fairly new to JavaScript and whenever I run cmd-here.bat (and after running "npm i") and type funi.js, I get this error.
![image](https://user-images.githubusercontent.com/34802341/117390286-df18e480-aebb-11eb-8475-70cda551206d.png)
How do I fix this?

**Comment by STRATOS99K** [comment]
use node funi
eg: node funi --auth

**Comment by thegreatuploader** [comment]
thank you!
