### ISSUE TITLE
I keep on getting the opinions screen

### ISSUE THREAD

**Issue by thegreatuploader** [anidl/funimation-downloader-nx#67]
I'm trying to download Shimoneta and after grabbing the show id, I put in this code
> node funi.js -s 36842 -e 1,2,3,4,5,6,7,8,9,10,11,12 -mks --dub

After I typed that in, I got the standard "USAGE: funi.js [options]" page and I do not know how to fix this.
I have already logged in and done "npm i"

**Comment by destromano** [comment]
`-mks` isn't a command. `--mks` will fix that line

**Comment by thegreatuploader** [comment]
Thank you! It works now.
