### ISSUE TITLE
MKVmerge error

### ISSUE THREAD

**Issue by thegreatuploader** [anidl/funimation-downloader-nx#68]
In my funimation folder, mkvmerge.exe is located in ./bin/mkvmerge, just like in the bin-path.yaml file. but after inputting my options I get this.
https://ghostbin.co/paste/d5s4m

**Comment by thegreatuploader** [comment]
I'm also using the newest version, 4.8.0-beta.1

**Comment by AnAppleforlife** [comment]
The version is full of bugs (especially regarding the new episodes). Try my fork of it, it fixes a lot of issues.

Can you please attach the bin-path.yml file as well as a screenshot of the mkvmerge.exe along the full path.

**Comment by thegreatuploader** [comment]
https://i.ibb.co/10bXYhm/image-2021-05-08-144023.png
https://drive.google.com/file/d/1oADKWOB_8km6bcaGNvrmxim0C5XlTtAH/view?usp=sharing

**Comment by AnAppleforlife** [comment]
Try to use './bin/mkvmerge/mkvmerge.exe'. It helped me

**Comment by thegreatuploader** [comment]
I got it to work! Thank you!
