### ISSUE TITLE
[BUG] invalid input file index when trying to download overlord

### ISSUE THREAD

**Issue by cimmy01** [anidl/funimation-downloader-nx#71]
** Main info: **

Script version: 4.8.0 beta 1.0
Show ID: 103522
Episode ID: 2

 "ffmpeg" -i "d:\downloaded\videos\[Funimation] Overlord - 02 [1080p].ts" -map 0 -map 1:a -c:v copy -c:a copy -metadata encoding_tool="no_variable_data" -metadata:s:v:0 title="[Funimation]" -metadata:s:a:0 language= "d:\downloaded\videos\[Funimation] Overlord - 02 [1080p].mp4"
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mpegts, from 'd:\downloaded\videos\[Funimation] Overlord - 02 [1080p].ts':
  Duration: 00:24:57.20, start: 1.440756, bitrate: 8275 kb/s
  Program 1
    Metadata:
      service_name    : Service
      service_provider: Hybrik
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 271 kb/s
Invalid input file index: 1.
(node:20156) UnhandledPromiseRejectionWarning: Error: Command failed: "u:\github\ffmpeg-4.2.2-win64-static\bin\ffmpeg.exe" -i "d:\downloaded\videos\[Funimation] Overlord - 02 [1080p].ts" -map 0 -map 1:a -c:v copy -c:a copy -metadata encoding_tool="no_variable_data" -metadata:s:v:0 title="[Funimation]" -metadata:s:a:0 language= "d:\downloaded\videos\[Funimation] Overlord - 02 [1080p].mp4"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.exec (U:\GitHub\funimation-downloader-nx-master\node_modules\sei-helper\src\main.js:174:30)
    at downloadStreams (U:\GitHub\funimation-downloader-nx-master\funi.js:719:14)
    at async getEpisode (U:\GitHub\funimation-downloader-nx-master\funi.js:376:13)
    at async getShow (U:\GitHub\funimation-downloader-nx-master\funi.js:253:13)
(node:20156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cimmy01** [comment]
I should mention that other shows are downloading just fine

**Comment by AnAppleforlife** [comment]
Which version are you using? The latest code of this repo?

**Comment by cimmy01** [comment]
yes I do have all of the pulls in and im on the latest build

**Comment by AnAppleforlife** [comment]
Can you try my [fork](https://github.com/AnAppleforlife/funimation-downloader-nx) (As long as the pull request isn't merged at least)? It tried to resolve as many issues as I could including some issues with FFmpeg.

**Comment by cimmy01** [comment]
Same issue I can mux it myself but its just odd

**Comment by AnAppleforlife** [comment]
Should have been resolved with #60. Get it from [here](https://github.com/AnAppleforlife/funimation-downloader-nx).

**Comment by cimmy01** [comment]
Looks like that got it. Thank You
