### ISSUE TITLE
Depreciated libraries

### ISSUE THREAD

**Issue by darkhelmet2016** [anidl/funimation-downloader-nx#73]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by AnAppleforlife** [comment]
Both are only used for building and are required by the packaged used for building. We can't do anything about it.

**Comment by darkhelmet2016** [comment]
Why was this closed when you have no idea what you are doing?
