### ISSUE TITLE
Audio saved as separate file

### ISSUE THREAD

**Issue by Millennion** [anidl/funimation-downloader-nx#74]
Command :

`node funi -s 20224 -q 10 --nosubs -e 681`

I've noticed this for at least 3 different animes. Random episodes in between will keep downloading as 2 files. One will be named `One Piece - 881 [1080p].ts` (containing the video, but no audio) and the other `One Piece - 881 [1080p].en.ts` (containing audio only).

Please let me know if you can reproduce this.

Many thanks!

**Comment by AnAppleforlife** [comment]
Hey there @Millennion. The program is working as intended. Funimation has changed how episodes work on newer stuff. Since they now offer more languages, audio and video have been separated. If you give the program mkvmerge or FFmpeg, it merges the two files into one for you.

**Comment by Millennion** [comment]
Hey, thanks for the quick reply! What exactly do you mean by "give the program mkvmerge or FFmpeg"?
Do you mean as arguments `--mkvmerge`? (I tried that, but didn't work).

**Comment by AnAppleforlife** [comment]
Open ```config/bin-path.yml```. There you can put the path to the programm (under Windows give the path to the .exe, e.g. ```C:\ffmpeg\ffmpeg.exe```

**Comment by chloudi** [comment]
Can you further explain on exactly what to do please? Sorry im really new to this and just got about 20 episodes that this did it too and cant for the life of me figure it out

**Comment by espher90** [comment]
@chloudi May you please check out the instructions I wrote here? https://github.com/anidl/funimation-downloader-nx/discussions/83

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
