### ISSUE TITLE
Request for instructions for beginners

### ISSUE THREAD

**Issue by jorgen639** [anidl/funimation-downloader-nx#78]
I am very interested in using this program, but the instructions are confusing for a non-programmer. If possible, may you or other users please explain step by step on how to use it? I have already downloaded the pre-requisites. Thank you all in advance.

**Comment by izu-co** [comment]
Please have a look at [this](https://github.com/anidl/funimation-downloader-nx/discussions/64#discussioncomment-701337) instruction I wrote a while ago (I still works so no worries).

Some questions are already answered in the comments, so if there are any issues have a look at it. 
If there are still some questions floating around in your head, just comment here again, and we will help you!
