### ISSUE TITLE
SOCKS5 Proxy Advice

### ISSUE THREAD

**Issue by valdearg** [anidl/funimation-downloader-nx#8]
Just been using the ripper and it seems to be working nicely.

One question I was just wanting a bit of advice on, I use a SOCKS5 proxy on localhost with port 4711.

I've tried with:

--proxy socks5://localhost:4711 = socket closed
--proxy localhost:4711 = cert_has_expired
--proxy http://localhost:4711 = ECONNRESET

**Comment by nijave** [comment]
` --proxy localhost:4711 = cert_has_expired` sounds like you have a proxy listening for https connections but the cert is no good? Does the proxy work for other things--it sounds like a proxy issue

**Comment by anidl** [comment]
proxy not supported right bow
