### ISSUE TITLE
[REQUEST] Support for subtitles in other languages

### ISSUE THREAD

**Issue by Oujiii** [anidl/funimation-downloader-nx#80]
** Main info: **

Script version: 4.8.0
Show ID: 1158133
Episode ID: 1

** Additional Info: **

This is just a request to use subtitles from other languages. Not sure if this feature is already there, but couldn't find anything on the docs.

**Comment by izu-co** [comment]
Hey there!

So the feature was already requested (among many other things and bug fixes) and I added it into #60. Unfortunately, the request want merged up until today. 
Therefore, you can find the code you need [here](https://github.com/izu-co/funimation-downloader-nx). If you have any issues feel free to open an issue here or [here](https://github.com/izu-co/funimation-downloader-nx).

Cheers
Izuco

(Just make sure you use the code version. If you need the release, message me (The current release is outdated))

**Comment by Oujiii** [comment]
Hey @izu-co, I'm using your code for a while, but  didn't know there was a `--subLang ` I could add into into it (and I just downloaded several anime, RIP). Can I add it to `cli-defaults.yml`?
Thank you!

**Comment by izu-co** [comment]
Hey @Oujiii, first, yes you can add it to ```cli-defaults.yml``` under ```subLang```. And thanks for the info with issues, you can now open one if you want!
