### ISSUE TITLE
Infinite 100% download

### ISSUE THREAD

**Issue by kahayes14** [anidl/funimation-downloader-nx#85]
I can't seem to figure out what is causing it, but when downloading large shows (movies is where I am running into it), the program gets stuck at 100% downloaded and then keeps outputting that over and over again, never continuing. I have already tried the --debug flag, but it doesn't give any info while it keeps repeating it. Any thoughts on this? The specific command run is `node funi -s 847520 -e M001 -q 0 --sub --debug`

**Comment by izu-co** [comment]
You may need to try my fork. 
This repository is outdated.
