### ISSUE TITLE
No sound from funi downloads

### ISSUE THREAD

**Issue by cimmy01** [anidl/funimation-downloader-nx#86]
Until yesterday the downloads were working fine. Today however they stopped getting sound on any attempt. This is the text I get after the download of the video finishes.

[INFO] Finished d:\downloaded\videos\[Funimation] Strike Witches - 08 [1080p].ts
[INFO] Downloading subtitles...
https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V1829107/ca42490e-4429-404a-95f0-279ff2022d51_english_CC.vtt
[INFO] Subtitles downloaded!

> "ffmpeg" -i "d:\downloaded\videos\[Funimation] Strike Witches - 08 [1080p].ts" -map 0 -c:v copy -c:a copy -metadata encoding_tool="no_variable_data" -metadata:s:v:0 title="[Funimation]" -metadata:s:a:0 language=eng "d:\downloaded\videos\[Funimation] Strike Witches - 08 [1080p].mp4"
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mpegts, from 'd:\downloaded\videos\[Funimation] Strike Witches - 08 [1080p].ts':
  Duration: 00:23:50.05, start: 10.041711, bitrate: 5996 kb/s
  Program 16727
    Stream #0:0[0x21]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
Output #0, mp4, to 'd:\downloaded\videos\[Funimation] Strike Witches - 08 [1080p].mp4':
  Metadata:
    encoding_tool   : no_variable_data
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      title           : [Funimation]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=34287 fps=26567 q=-1.0 Lsize= 1019793kB time=00:23:49.97 bitrate=5842.2kbits/s speed=1.11e+03x
video:1019297kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.048688%

[INFO] Done!

**Comment by izu-co** [comment]
This tool is way outdated. See my [fork](https://github.com/izu-co/funimation-downloader-nx) for a maintained version.

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
