### ISSUE TITLE
Wiki needed?

### ISSUE THREAD

**Issue by izu-co** [anidl/funimation-downloader-nx#90]
I want to use this issue to ask the community whether a wiki is needed.

The wiki would explain how to use this tool, as well as explain all the different options that can or must be used.

**Comment by bgette** [comment]
i think the better solution is open an telegram no?
anyway, maybe u can do a videos it will be more simple

**Comment by izu-co** [comment]
I like the idea of videos. 

However, in my country telegram is mostly used by anti-government groups (or at least it has the reputation of) so I don't really like it.

**Comment by DragonVsKira** [comment]
this is where my GUI will help out lol
i say no to wiki do not what it to get fix/patch
videos maybe

**Comment by arbarbosa1979** [comment]
Yes, I think a wiki or help would be interesting at this point.

**Comment by izu-co** [comment]
@DragonVsKira I am talking about a kind of tutorial for the cli.

Like where to get the ID from. How does the file template work. And so on

**Comment by DragonVsKira** [comment]
so something  like this lol @izu-co 
it just part 1 lol
https://drive.google.com/drive/folders/1epFgF2fJblJto4dSqbBi0AmTeAt6s8Y9?usp=sharing

**Comment by izu-co** [comment]
Yes

**Comment by DragonVsKira** [comment]
i can do more ? if u thank it helpful ?
sorry for no mic

**Comment by NatsuFT36** [comment]
Hi, I wish you could add for the server formats of the previous season in Funimation on Cloudfront with audio from 128 to 256kbps d33et77evd9bgg.cloudfront.net

**Comment by NapoleonPR0** [comment]
Hello how are all my friends in these comments, I would like to communicate with the developer of this Funimation videos script, I would like to tell him that a group could be created in mesemger, in whatsapp or in tekegram or in Discord, I have doubts about his commands I have tried everything possible and I do not get the videos to download from the Funimation platform, I was looking for two days and I gave up, I am too sad, I did not want my time to be wasted.

**Comment by bgette** [comment]
> Hello how are all my friends in these comments, I would like to communicate with the developer of this Funimation videos script, I would like to tell him that a group could be created in mesemger, in whatsapp or in tekegram or in Discord, I have doubts about his commands I have tried everything possible and I do not get the videos to download from the Funimation platform, I was looking for two days and I gave up, I am too sad, I did not want my time to be wasted.

send your command

**Comment by DragonVsKira** [comment]
@NapoleonPR0 the videos was only about how to get the anime show ID that all not how to Download that way going to be in part 02 if people what it ps u need funimation subscription

**Comment by izu-co** [comment]
@NapoleonPR0 Please open a new issue for questions. This issue only asked the community whether an expiation is needed. 
@NatsuFT36 Same goes for you. If you have any requests or issues, open a new issue, please.

**Comment by DragonVsKira** [comment]
@izu-co do u thank it will be helpful
if not im not going to make anymore just asking
u can mark this off topic when done reading it
or if u r going to do video ill leave it to u

**Comment by izu-co** [comment]
Btw y all you can look under the wiki tab to see what I meen.

**Comment by izu-co** [comment]
This is a lot to write tho so if you want to write a section for a command like `-e` just write me an email to github@izuco.dev

**Comment by NapoleonPR0** [comment]
Hello, good morning, script administrator, I already sent you a message to your email that you published, I sent it through Google Gmail, thank you very much, I will look forward to your response. :D

**Comment by DragonVsKira** [comment]
lol when u sad wiki i was thinking the website not the github wiki tab lol im a noob im down for that ps it looking good

**Comment by NapoleonPR0** [comment]
Hopefully you can help me in this Funimation script.

**Comment by DragonVsKira** [comment]
@NapoleonPR0 Please open a new issue for questions. This issue only asked the community 
then ill try to help u

**Comment by NapoleonPR0** [comment]
How to open the question form?

**Comment by DragonVsKira** [comment]
![New Issue · ani](https://user-images.githubusercontent.com/35433196/129742143-d1609c80-5a7e-47c5-8dd8-a19ce36e72c1.png)

**Comment by izu-co** [comment]
The question has been resolved. A wiki would be needed and if I find time I will add more stuff to it, community input is always appreciated tho.
