### ISSUE TITLE
Use of server in Funimation for the previous season (Spring 2021) with the audio formats

### ISSUE THREAD

**Issue by NatsuFT36** [anidl/funimation-downloader-nx#94]
As you know there were errors in the previous version due to an update on the Funimation page so I changed their videos and audios separately and that changed a lot since the audios were 253 kbps and now they come out with 128 kbps.

On servers like Golumpa he got the audio formats and changed them to 256 kbps but it was that they used Cloudfront (one more server from Funimation) as a download server and that is how their use of quality appeared.

In this new Summer season, Funimation changed its audio format to 256 kbps and reordered its video format from low to high quality in its player.

The link they used for audio enhancements on the Funimation server is: d33et77evd9bgg.cloudfront.net

**Comment by izu-co** [comment]
I don't really know what's the problem. Can you explain it to me please?

**Comment by NatsuFT36** [comment]
What happens is when I download the chapter either Combatants Will Be Dispatched! In dubbing format either English or Spanish, its audio represents 128kbps with respect to what goes up in torrents like Golumpa's, which comes out with 256kbps audio.

Another detail is that from a page called Dirpy I tried it with the same series with the Japanese language and with the video in 540p and it came out with 256kbps audio compared to what I tested with his, which came out with 128kbps audio.

**Comment by izu-co** [comment]
So basically you are telling me that you found the videos on other sites in better audio quality.

**Comment by NatsuFT36** [comment]
Yes, since this I tried it with one of the free chapters of the spring season and I noticed that the audio went to 256kbps and instead what I download through cli I get 128kbps.

This I went to Dirpy's page: https://dirpy.com

**Comment by izu-co** [comment]
Can you tell me the show and episode ID?

**Comment by NatsuFT36** [comment]
https://www.funimation.com/es-mx/shows/combatants-will-be-dispatched/how-to-defeat-an-evil-leader

![Captura24](https://user-images.githubusercontent.com/51544427/130192119-442e7a75-9daf-4067-9224-ddbb6a41a0da.PNG)

**Comment by NatsuFT36** [comment]
From there you can see the site from the video that server is used and the previous download in 540p of video and 256kbps audio

**Comment by NatsuFT36** [comment]
In funimation downloader nx the title id comes out: 1396445

**Comment by izu-co** [comment]
As you can see the first episode of the show only has 128kbps audio: 

```json
"mediaGroups": {
        "AUDIO": {
            "audio-aacl-128": {
                "English": {
                    "default": true,
                    "autoselect": true,
                    "language": "en",
                    "uri": The URL"
                }
            }
        },
        "VIDEO": {},
        "CLOSED-CAPTIONS": {},
        "SUBTITLES": {}
    }
```

**Comment by izu-co** [comment]
I don't know where dirpy gets the better audio from (maybe it just artificially raises the bitrate?), but I don't see an error with the cli.
