### ISSUE TITLE
Record of Grancrest War - S1E5 will not DL [BUG] 

### ISSUE THREAD

**Issue by DragonVsKira** [anidl/funimation-downloader-nx#95]
** Main info: **

Script version: 4.9.4
Show ID: 1161184
Episode ID: 5
Command used:
`funi -s 1161184 -e 5  -q "10" --mkv --mks --allSubs --fileName --fileName "${showTitle} - S${season}E${episode} - ${title} - [${height}p] [FuniDub][DVK]"`
** Additional Info: **
[INFO] Selected Episodes: 0005

[INFO] Record of Grancrest War - S1E5 - Forest of Eternal Darkness
[INFO] Available streams (Non-Encrypted):
[#1162571] English [Uncut] (selected)
[#1162518] Japanese [Uncut]
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (529KiB/s)
         2: 480x270 (765KiB/s)
         3: 640x360 (988KiB/s)
         4: 640x360 (1729KiB/s)
         5: 960x540 (2370KiB/s)
         6: 1280x720 (2984KiB/s)
         7: 1280x720 (4323KiB/s)
         8: 1440x810 (6082KiB/s)
         9: 1920x1080 (7832KiB/s)
        10: 1920x1080 (9597KiB/s)
[INFO] Selected layer: 10 (1920x1080) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2275015/English/2275015_English_17647033-b1f7-ea11-82a8-dd291e252010_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMjc1MDE1L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyOTI2Nzg2MH19fV19&Signature=pKF5sIwMVt8-FS~p82EFetaBWEjOT0fp9s9vEKVJrdekd353XH6tS~Qks2NJnnWxtnYU7kUQwX-eM08sFqClREKPQFuTPTCV94fLU1ZCUFu-VN~PpvyuULFSWBJKsbXq2YDvg4PUAYUqGZcKoyW8faZSM903RkjWlsN6Ay5IyUgcZCsc8QPwz3SV1xx0Ckt~ttLBJY9-yg~EXObaBlv24eroktc~zeaXzyaz~AKr-48yXOrI4DDqcbuggohCXye2ya4CLyFt8Z1FbeUoRl0xmwQtb6HQB~ts9-mKtNppEc098YxJjLm-eaJvUptZynPCZiYJqLwYsft-v-ZQtOOYaQ__&rt=1432884
[INFO] Output filename: Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [1080p] [FuniDub][DVK].ts
[INFO] Started C:\funidownloader-nx\funimation-downloader-nx-win64\videos\Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [1080p] [FuniDub][DVK].video.en.ts
[INFO] 10 of 179 parts downloaded [6%] (23s)
[INFO] 20 of 179 parts downloaded [11%] (24s)
[INFO] 30 of 179 parts downloaded [17%] (24s)
[INFO] 40 of 179 parts downloaded [22%] (25s)
[INFO] 50 of 179 parts downloaded [28%] (26s)
[INFO] 60 of 179 parts downloaded [34%] (24s)
[INFO] 70 of 179 parts downloaded [39%] (21s)
[INFO] 80 of 179 parts downloaded [45%] (19s)
[INFO] 90 of 179 parts downloaded [50%] (17s)
[INFO] 100 of 179 parts downloaded [56%] (15s)
[INFO] 110 of 179 parts downloaded [61%] (14s)
[INFO] 120 of 179 parts downloaded [67%] (11s)
[INFO] 130 of 179 parts downloaded [73%] (9s)
[INFO] 140 of 179 parts downloaded [78%] (7s)
[INFO] 150 of 179 parts downloaded [84%] (6s)
[INFO] 160 of 179 parts downloaded [89%] (4s)
[INFO] 170 of 179 parts downloaded [95%] (2s)
[ERROR] HTTPError: Response code 403 (Forbidden)
[ERROR] HTTPError: Response code 403 (Forbidden)
[ERROR] HTTPError: Response code 403 (Forbidden)
[ERROR] HTTPError: Response code 403 (Forbidden)
[ERROR] An error occured while downloading C:\funidownloader-nx\funimation-downloader-nx-win64\videos\Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [1080p] [FuniDub][DVK].video.en.ts

[INFO] Unable to locate a video AND audio file

**on layer: 8 i get this** 

[INFO] Selected layer: 8 (1440x810) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2275015/English/2275015_English_17647033-b1f7-ea11-82a8-dd291e252010_Layer8.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMjc1MDE1L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyOTI2NzM3MH19fV19&Signature=OwNqiU1T7HoSbe9zf5YrfbzGIbQskoL1R-UpL8k5FL3~SyDQ7n-u7pcz6fcUTL3V9N3AQAipH-JSQpgZ~cQDqTBWqocapxY1neqvsPee-L2aB9vqA4n7BQqJ1TF4OSlwVKotppGPSwhrFo2pSHGuCQicxEe9QaeKEHGE4L5mmMCJ2OW4zjGctgcUBlcFbUmpjjeiPiS1AfrLYMekEZm~ex-cfGOebDZaLOYqOZszDyM6pxsVaNOnONMwBMzSXNWhLiToMUCnOwBPm2jamlO0q4EPLMG1WT4R1o9ZdLTr59iLIUEwIPO3qUTCe7Jz1mFWRdy0C4TrJPzybsWMjHf4SA__&rt=1432884
[INFO] Output filename: Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [810p] [FuniDub][DVK].ts
[INFO] Started C:\funidownloader-nx\funimation-downloader-nx-win64\videos\Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [810p] [FuniDub][DVK].video.en.ts
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] HTTPError 403: Forbidden
[ERROR] Can't get key
[ERROR] An error occured while downloading C:\funidownloader-nx\funimation-downloader-nx-win64\videos\Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [810p] [FuniDub][DVK].video.en.ts

[INFO] Unable to locate a video AND audio file

and yes i relog-in to did not fix it 

**on layer: 7 i get this** 

[INFO] Selected layer: 7 (1280x720) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2275015/English/2275015_English_17647033-b1f7-ea11-82a8-dd291e252010_Layer7.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMjc1MDE1L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyOTI2ODI3NX19fV19&Signature=J7XkD-4~V9gXwyV2ctuJ9DYmf2AKz12vTaD3sIoMN1g2g7A6k8CXLt3BJaSHWMQMc3936JzGjTBd8QZdayf1xyaKDIcAQf9ZWZN1HiK8-DoaC1h6i30pfPGVsQ1hkS~GAhZbYm3x-EEPN8UBlf3vtY2acOG4tBbZ4iAi-kIfJZ7A65IupB20yIGRzKE-Bb308HnMxu3dog~OwSuj7yn9TV~sIJCQTmnZCJxBMd0Q7wNkpeIEA8lXEKG7toSihelS~AOYKwLsaFRcV363YmUvtHEKeVblbFkftRheyG8k625UYvRnqFvdDdtfa29vaOPen0dp1h7Eag16NVBF220wtA__&rt=1432884
[INFO] Output filename: Record of Grancrest War - S01E05 - Forest of Eternal Darkness - [720p] [FuniDub][DVK].ts
[ERROR] HTMLError:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>0G6W66V8H1H36P1G</RequestId><HostId>JWBxHO/nmWIbTMwtRPuIp3WrPlPffDPrAtwzC7N+qe9p6Yy1dz/uB17AxH+wfWzo5kHDrmBnvt0=</HostId></Error>

** PS it look like only Japanese work im lost now**

**Comment by izu-co** [comment]
Just cheked this on funimation itself. 
![grafik](https://user-images.githubusercontent.com/57068530/129876399-1d3793e7-fc4a-4e89-89ca-702156d63dea.png)
As you can see, this issue is not related to the downloader, but rather to Funimation isself.

**Comment by DragonVsKira** [comment]
Ok u can close this or leave it open so other people will now ….”It up to u”

 Thanks for checking it out for me
